# Generated by Django 6.0.3 on 2026-03-23 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='resolved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='found_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
