# Generated by Django 6.0.3 on 2026-04-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_claim_resolved_alter_item_found_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Lost', 'Perdido'), ('Found', 'Encontrado')], default='Lost', max_length=10),
        ),
        migrations.DeleteModel(
            name='ItemStatus',
        ),
    ]
