# Generated by Django 6.0.3 on 2026-04-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_status_delete_itemstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact_info',
            field=models.CharField(default='hola', max_length=255),
            preserve_default=False,
        ),
    ]
