# Generated by Django 6.0.3 on 2026-04-27 21:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_contact_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='found_date',
        ),
        migrations.AddField(
            model_name='item',
            name='lost_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha en que se perdió'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemcategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemcolor', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='item',
            name='contact_info',
            field=models.CharField(max_length=255, verbose_name='Información de contacto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='item',
            name='creator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reportó el objeto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción del objeto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items/', verbose_name='Imagen del objeto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre del objeto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Lost', 'Perdido'), ('Found', 'Encontrado')], default='Lost', max_length=10, verbose_name='Estado del objeto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campuszone', verbose_name='Zona'),
        ),
    ]
