# Generated by Django 6.0.3 on 2026-04-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_item_found_date_item_lost_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuszone',
            options={'verbose_name': 'Zona del campus', 'verbose_name_plural': 'Zonas del campus'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Objeto', 'verbose_name_plural': 'Objetos'},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name': 'Categoría de objeto', 'verbose_name_plural': 'Categorías de objetos'},
        ),
        migrations.AlterModelOptions(
            name='itemcolor',
            options={'verbose_name': 'Color de objeto', 'verbose_name_plural': 'Colores de objetos'},
        ),
        migrations.AlterField(
            model_name='campuszone',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='campuszone',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='campuszone',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='campuszone',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='campuszone',
            name='zone',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='category',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='color',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
